{% set name = "yamlordereddictloader" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f30f0b99ea3f877f7cb340c570921fa9d639b7f69cba18be051e27f8de2080e

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - yamlordereddictloader

about:
  home: https://github.com/fmenabe/python-yamlordereddictloader
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: YAML loader and dump for PyYAML allowing to keep keys order.

extra:
  recipe-maintainers:
    - PertuyF
    - bgruening
